package controller;

public enum Action {
	MANAGER, USER, SHOW_DIALOD_ADD, ADD, REMOVE, ADD_IMAGE, SHOW_DIALOG_EDIT, EDIT, SHOW_DIALOG_DETAILS, PAGE_PREVIEW_ADMIN, PAGE_PREVIEW_USER, PAGE_NEXT_ADMIN, PAGE_NEXT_USER, FILTER_USER, BUY_PRODUCT, BUY_ALL, LOGOUT, CANCELE, SHOPPING, FILTER_FOR_TYPE_PRODUCT, ADD_SHOPING, SHOW_DIALOGSHOPING;
}